apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: splunk
- allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegeEscalation: true
  allowPrivilegedContainer: false
  allowedCapabilities: []
  apiVersion: security.openshift.io/v1
  defaultAddCapabilities: null
  fsGroup:
    type: RunAsAny
  groups: []
  kind: SecurityContextConstraints
  metadata:
    name: splunk-scc
  priority: null
  readOnlyRootFilesystem: false
  requiredDropCapabilities: []
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  users:
  - system:serviceaccount:splunk:splunk
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
- apiVersion: v1
  stringData:
    admin-password: ChangeMeSuperSecure123!
    hec-token: 00000000-0000-0000-0000-000000000000
  kind: Secret
  metadata:
    name: splunk-secrets
    namespace: splunk    
  type: Opaque
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: splunk
    namespace: splunk
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: splunk
    serviceName: splunk
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: splunk
      spec:
        containers:
        - env:
          - name: SPLUNK_GENERAL_TERMS
            value: --accept-sgt-current-at-splunk-com
          - name: SPLUNK_START_ARGS
            value: --accept-license
          - name: SPLUNK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin-password
                name: splunk-secrets
          image: splunk/splunk:latest
          imagePullPolicy: Always
          name: splunk
          ports:
          - containerPort: 8000
            name: web
            protocol: TCP
          - containerPort: 8088
            name: hec
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /en-US/account/login
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/splunk/var
            name: splunk-pvc
          - mountPath: /opt/splunk/etc/system
            name: splunk-etc
            subPath: system
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - /bin/sh
          - -c
          - /init/init.sh
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          name: prepare-config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /init
            name: init-scripts
          - mountPath: /etc-out
            name: splunk-etc
          - mountPath: /run/secret-hec
            name: secret-hec
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 2000
          fsGroupChangePolicy: OnRootMismatch
        serviceAccount: splunk
        serviceAccountName: splunk
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: splunk-etc
        - configMap:
            defaultMode: 493
            name: splunk-init
          name: init-scripts
        - name: secret-hec
          secret:
            defaultMode: 420
            items:
            - key: hec-token
              path: hec-token
            secretName: splunk-secrets
        - name: splunk-pvc
          persistentVolumeClaim:
            claimName: splunk-pvc
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: splunk-85c9869bcc
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: splunk-85c9869bcc
    updatedReplicas: 1
- apiVersion: v1
  data:
    init.sh: |
      #!/usr/bin/env sh
      set -euo pipefail

      # Write directly into the mounted emptyDir (shared with main container)
      mkdir -p /etc-out/system/local

      # Create a metrics index for k8s/Kasten data
      cat >/etc-out/system/local/indexes.conf <<'EOF'
      [k8s_metrics]
      datatype = metric
      homePath = $SPLUNK_DB/k8s_metrics/db
      coldPath = $SPLUNK_DB/k8s_metrics/colddb
      thawedPath = $SPLUNK_DB/k8s_metrics/thaweddb
      EOF

      # Enable HEC and register our token/input that targets the metrics index
      HEC_TOKEN="$(cat /run/secret-hec/hec-token)"
      cat >/etc-out/system/local/inputs.conf <<EOF
      [http]
      disabled = 0
      enableSSL = 1
      port = 8088

      [http://otel-hec]
      disabled = 0
      token = ${HEC_TOKEN}
      index = k8s_metrics
      source = kasten
      sourcetype = metrics
      EOF
  kind: ConfigMap
  metadata:
    name: splunk-init
    namespace: splunk    
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: splunk-pvc
    namespace: splunk    
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi      
- apiVersion: v1
  kind: Service
  metadata:
    name: splunk
    namespace: splunk    
  spec:    
    ports:
    - name: web
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: hec
      port: 8088
      protocol: TCP
      targetPort: 8088
    selector:
      app: splunk
    sessionAffinity: None
    type: ClusterIP  
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: web
    namespace: splunk    
  spec:    
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: splunk
      weight: 100
    wildcardPolicy: None  
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: splunk
    namespace: splunk  
kind: List
metadata:
  resourceVersion: ""
